### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method getInstallSourceInfo

### ISSUE THREAD

**Issue by d4rken** [d4rken/mystic-permissions#32]
@d4rken I'm not sure if this is the exact issue they're talking about, but I get this crash at runtime (version 0.2.0).

My device is a Samsung Note 9 running Android 10.

```
FATAL EXCEPTION: DefaultDispatcher-worker-6
Process: eu.darken.myperm, PID: 16028
java.lang.NoSuchMethodError: No virtual method getInstallSourceInfo(Ljava/lang/String;)Landroid/content/pm/InstallSourceInfo; in class Landroid/content/pm/PackageManager; or its super classes (declaration of 'android.content.pm.PackageManager' appears in /system/framework/framework.jar)
	at eu.darken.myperm.apps.core.installer.InstallerInfoKt.getInstallerInfoLegacy(InstallerInfo.kt:69)
	at eu.darken.myperm.apps.core.installer.InstallerInfoKt.getInstallerInfo(InstallerInfo.kt:54)
	at eu.darken.myperm.apps.core.AppRepo.toDefaultApp(AppRepo.kt:82)
	at eu.darken.myperm.apps.core.AppRepo.access$toDefaultApp(AppRepo.kt:26)
	at eu.darken.myperm.apps.core.AppRepo$apps$1.invokeSuspend(AppRepo.kt:43)
	at eu.darken.myperm.apps.core.AppRepo$apps$1.invoke(Unknown Source:8)
	at eu.darken.myperm.apps.core.AppRepo$apps$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:214)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Unknown Source:13)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:34)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:8)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:33)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:398)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invokeSuspend(Merge.kt:27)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Unknown Source:8)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest.flowCollect(Merge.kt:25)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(Unknown Source:0)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6b0b2cc, Dispatchers.Default]
```

_Originally posted by @TacoTheDank in https://github.com/d4rken/mystic-permissions/issues/25#issuecomment-1186967842_

**Comment by d4rken** [comment]
Without a stacktrace i don't know if it's the same as #25 :shrug:, splitting this into a new ticket because this will be an easy fix.

I mixed up the API level check. It runs the higher API version on the lower API and vice versa :sweat: 

This is not the legacy api I'm calling the in `...Legacy` function :-1: 

https://github.com/d4rken/mystic-permissions/blob/6215cebb42f0694df143052afa9d29c3925724a9/app/src/main/java/eu/darken/myperm/apps/core/installer/InstallerInfo.kt#L67-L72****

Good catch, thanks!

**Comment by d4rken** [comment]
@TacoTheDank should be fixed in 0.2.1 (currently building)

**Comment by TacoTheDank** [comment]
Thanks!
