### ISSUE TITLE
0.0.7 to 0.0.9 crashes

### ISSUE THREAD

**Issue by dragonGod97677** [d4rken/mystic-permissions#8]
Yup it crashes on my device

**Comment by dragonGod97677** [comment]
App needs verbose log debugging enabled by default on dev builds and disabled and optional can be enabled by user by default on beta and release/stable builds

**Comment by dragonGod97677** [comment]
Also add a label like this
![Screenshot_2022-07-17-10-13-04-84](https://user-images.githubusercontent.com/38875906/179381099-99ab715c-5f20-47ad-a8f9-ba7ffa89544c.png)
To let the user know that it is a stable/beta/dev build and what variant (foss/gplay)

**Comment by d4rken** [comment]
Please share a stacktrace of the crash or a system bug report.

**Comment by dragonGod97677** [comment]
[2022@07@17@CPH1803EX_11.A.34_0340_202101221404@eu.darken.myperm@data_app_crash@9902646943_1658022694245_1658022695473.txt](log)


My device is oppo a3s, Android 8

**Comment by d4rken** [comment]
```java
android.content.pm.PackageManager$NameNotFoundException: pc
	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:186)
	at eu.darken.myperm.apps.core.AppRepo.getInstaller(AppRepo.kt:105)
	at eu.darken.myperm.apps.core.AppRepo.toDefaultApp(AppRepo.kt:83)
	at eu.darken.myperm.apps.core.AppRepo.access$toDefaultApp(AppRepo.kt:27)
	at eu.darken.myperm.apps.core.AppRepo$apps$1.invokeSuspend(AppRepo.kt:44)
	at eu.darken.myperm.apps.core.AppRepo$apps$1.invoke(Unknown Source:8)
	at eu.darken.myperm.apps.core.AppRepo$apps$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:214)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Unknown Source:13)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:34)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:8)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:33)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:398)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invokeSuspend(Merge.kt:27)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Unknown Source:8)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest.flowCollect(Merge.kt:25)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(Unknown Source:0)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@cf41102, Dispatchers.Default]
```

**Comment by d4rken** [comment]
@dragonGod97677 v0.1.2 should fix this, currently being build. :+1:
